# system configuration
system:
  env: develop
  addr: 8888
  i18n: "locale.json"
  website: ""
# pgsql configuration
pgsql:
  path: "127.0.0.1"
  port: "5432"
  config: ""
  db-name: ""
  username: "postgres"
  password: "123456"
  auto-migrate: true
  prefix: ""
  slow-threshold: 200
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# redis configuration
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
  prefix: "decert:"

# log configuration
log:
  level: info
  save: true
  format: console
  log-in-console: true
  prefix: '[backend-go]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace


# auth configuration
auth:
  signing-key: "Decert"
  expires-time: 86400
  issuer: "Decert"

# local configuration
local:
  path: 'uploads/file'
  ipfs: 'uploads/ipfs'

# blockchain configuration
blockchain:
  ens-rpc: "https://rpc.ankr.com/eth"
  sign-private-key: ""
  signature: "Welcome to Decert!\n\nThis request will not trigger a blockchain transaction or cost any gas fees.\n\nYour authentication status will reset after 24 hours.\n\n"
  signature-exp: 240

# contract configuration
contract:
  badge: "0xaD1789A4cA2640a570a1268c84EA87e09A10A1f5"
  quest: "0xd1E50047cEbaD1d826c3F7961A35048B518652F2"
  quest-minter: "0xeb4E2EE6f165e7E1B9a4F1c4532C0433a6Ef397B"

# quest configuration
quest:
  encrypt-key: "eb5a5bb2-ebbd-45cc-9d37-77a9377f2aca"

# ipfs configuration
ipfs:
  - api: "https://ipfs.io/ipfs"
    upload-api: "http://192.168.1.10:3022/v1"

# judge configuration
judge:
  judge-api:
    - url: "http://192.168.1.10:3022/v1"
      weight: 10