# system configuration
system:
  env: develop
  addr: 8888

# pgsql configuration
pgsql:
  path: "127.0.0.1"
  port: "5432"
  config: ""
  db-name: ""
  username: "postgres"
  password: "123456"
  auto-migrate: true
  prefix: ""
  slow-threshold: 200
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# log configuration
log:
  level: info
  save: true
  format: console
  log-in-console: true
  prefix: '[backend-go]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace


# auth configuration
auth:
  signing-key: "Decert"
  expires-time: 86400
  issuer: "Decert"

foundry:
  work-path: "/Users/mac/Code/cloud-run-foundry"

# quest configuration
quest:
  encrypt-key: "Pz8HN1LAD7Q2C6gvQewnM3pxFvLeO8z8eKNnWxGQ"

judge:
  work-path: "/Users/mac/Code/resource/"
  cache-path: "/Users/mac/Code/resource/cache"

docker:
  clear-enabled: true
  clear-time: 15