# system configuration
system:
  env: develop
  addr: 8888

# pgsql configuration
pgsql:
  path: "127.0.0.1"
  port: "5432"
  config: ""
  db-name: ""
  username: "postgres"
  password: "123456"
  prefix: ""
  slow-threshold: 200
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# redis configuration
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
  prefix: "decert:"

# zap configuration
zap:
  level: info
  format: console
  prefix: '[backend-go]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

# jwt configuration
jwt:
  signing-key: "Decert"
  expires-time: 86400
  issuer: "Decert"

# local configuration
local:
  path: 'uploads/file'

# blockchain configuration
blockchain:
  private-key: ""
  provider: "https://rpc.ankr.com/eth_goerli"

# contract configuration
contract:
  badge: "0xaD1789A4cA2640a570a1268c84EA87e09A10A1f5"
  quest: "0xd1E50047cEbaD1d826c3F7961A35048B518652F2"
  quest-minter: "0xeb4E2EE6f165e7E1B9a4F1c4532C0433a6Ef397B"
  signature: "Welcome to Decert!\n\nThis request will not trigger a blockchain transaction or cost any gas fees.\n\nYour authentication status will reset after 24 hours.\n\n"

# twitter configuration
twitter:
  bear-token: ""
  claim-content: "我通过了@DecertMe的挑战并获得了一个链上的能力认证徽章。\nhttps://decert.me/quests/\n#Decert.me"

scheduler:
  active: true
  airdrop-badge: "15 * * * *"