# system configuration
system:
  env: develop
  addr: 8888

# pgsql configuration
pgsql:
  path: "127.0.0.1"
  port: "5432"
  config: ""
  db-name: ""
  username: "postgres"
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# zap configuration
zap:
  level: info
  format: console
  prefix: '[backend-go]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

# local configuration
local:
  path: 'uploads/file'

# blockchain configuration
blockchain:
  private-key: ""
  provider: "https://rpc.ankr.com/eth_goerli"