# pgsql configuration
pgsql:
  path: "127.0.0.1"
  port: "5432"
  config: ""
  db-name: ""
  username: "postgres"
  password: "123456"
  auto-migrate: true
  prefix: ""
  slow-threshold: 200
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# log configuration
log:
  level: info
  save: true
  format: console
  log-in-console: true
  prefix: '[backend-go]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace

# blockchain configuration
blockchain:
  sign-private-key: ""
  airdrop-private-key: ""
  chain-id: 5
  attempt: 200
  provider:
    - url: "https://rpc.ankr.com/eth_goerli"
      weight: 5
    - url: "https://rpc.ankr.com/eth_goerli"
      weight: 10

# contract configuration
contract:
  badge: "0xaD1789A4cA2640a570a1268c84EA87e09A10A1f5"
  quest: "0xd1E50047cEbaD1d826c3F7961A35048B518652F2"
  quest-minter: "0xeb4E2EE6f165e7E1B9a4F1c4532C0433a6Ef397B"
  
# twitter configuration
twitter:
  bear-token: ""
  claim-content: ["Glad to have completed a new challenge 💪🏻  .\n\nI just claimed a free NFT badge from @decertme.\n\n Meeting the challenge and claim yours at https://decert.me/quests/\n\n #DeCert","很高兴完成了一个新的挑战 💪🏻  。\n\n我从 @decertme 获得一个 NFT 勋章。\n\n 你也可以参与挑战：https://decert.me/quests/\n\n #DeCert"]
# scheduler configuration
scheduler:
  active: true
  airdrop-badge: "15 * * * *"

ipfs:
  api: "https://ipfs.io/ipfs/"