# pgsql configuration
pgsql:
  path: "127.0.0.1"
  port: "5432"
  config: ""
  db-name: ""
  username: "postgres"
  password: "123456"
  auto-migrate: true
  prefix: ""
  slow-threshold: 200
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# log configuration
log:
  level: info
  save: true
  format: console
  log-in-console: true
  prefix: '[backend-go]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace

# blockchain configuration
blockchain:
  sign-private-key: ""
  airdrop-private-key: ""
  chain-id: 5
  attempt: 200
  provider:
    - url: "https://rpc.ankr.com/eth_goerli"
      weight: 5
    - url: "https://rpc.ankr.com/eth_goerli"
      weight: 10

# contract configuration
contract:
  badge: "0xaD1789A4cA2640a570a1268c84EA87e09A10A1f5"
  quest: "0xd1E50047cEbaD1d826c3F7961A35048B518652F2"
  quest-minter: "0xeb4E2EE6f165e7E1B9a4F1c4532C0433a6Ef397B"
  
# twitter configuration
twitter:
  bear-token: ""
  claim-content: "我通过了 @DecertMe 上完成了一个挑战并获得了链上能力认证的徽章。\nhttps://decert.me/quests/\n#DecertMe"


# scheduler configuration
scheduler:
  active: true
  airdrop-badge: "15 * * * *"