# system configuration
system:
  env: develop
  addr: 8889
  i18n: "locale.json"

# pgsql configuration
pgsql:
  path: "127.0.0.1"
  port: "5432"
  config: ""
  db-name: "decert"
  username: "postgres"
  password: "123456"
  auto-migrate: true
  prefix: ""
  slow-threshold: 200
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# log configuration
log:
  level: info
  save: true
  format: console
  log-in-console: true
  prefix: '[backend-go]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace


# auth configuration
auth:
  auth:
    signing-key: "Decert"
    expires-time: 86400
    issuer: "Decert"
  twitter:
    consumer-key: ""
    consumer-secret: ""
    callback-url: "https://decert.me/callback/twitter"
    bearer-token: ""