# system configuration
system:
  env: develop
  addr: 8889

# log configuration
log:
  level: info
  save: true
  format: console
  log-in-console: true
  prefix: '[backend-go]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace


# auth configuration
auth:
  wechat:
    app-id: ""                    # wechat app id
    app-secret: ""                # wechat app secret
    token: ""                     # wechat token
    encoding-aes-key: ""          # wechat encoding aes key(可选)
  discord:
    client-id: ""
    client-secret: ""
  github:
    client-id: ""
    client-secret: ""

# project configuration
project:
  decert:
    api-key: "test"
    callback-url: "http://127.0.0.1:8087/api"